### PR TITLE
Fix #5 by sorting indexes in `HyphenIndexFinder`

### LINKED ISSUE #5: Long words give unordered indexes, which breaks output
During `HyphenatedToken#read`, the hyphenated string is reconstituted using the indexes found by `HyphenIndexFinder#findIndexes`. However, these are not always ordered, and will lead to exceptions such as the following:

```
Exception in thread "main" java.lang.IndexOutOfBoundsException: Range [24, 9) out of bounds for length 27
	at java.base/jdk.internal.util.Preconditions$3.apply(Preconditions.java:71)
	at java.base/jdk.internal.util.Preconditions$3.apply(Preconditions.java:68)
	at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:213)
	at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:210)
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:98)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckFromToIndex(Preconditions.java:112)
	at java.base/jdk.internal.util.Preconditions.checkFromToIndex(Preconditions.java:349)
	at java.base/java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:684)
	at java.base/java.lang.StringBuilder.append(StringBuilder.java:218)
	at io.github.nianna.api.HyphenatedToken.read(HyphenatedToken.java:40)
	at io.github.nianna.api.HyphenatedText.lambda$read$0(HyphenatedText.java:57)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:722)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at io.github.nianna.api.HyphenatedText.read(HyphenatedText.java:58)
```

For some reason, this happened easily for me when hyphenating in Danish. I could not reproduce this with Polish words and the Polish pattern list.

### PR DESCRIPTION
**Pull request by jespersm**
* Adds test case for long Danish word to show problem
* Fixes problem with non-increasing hyphenation positions
* Also adds Danish pattern list from tex-hyphen as test resource.

### CODE REVIEW

File: src/test/java/io/github/nianna/TestUtil.java [hunk 1]
```diff
@@ -38,4 +38,14 @@ public static List<String> loadPlPatterns() {
         }
     }
 
+    public static List<String> loadDaPatterns() {
+        try {
```
Comment (Nianna) [inline src/test/java/io/github/nianna/TestUtil.java:40]: Please extract private method called e.g. _loadPatterns(String sourceFile)_ to avoid copying code

**Review by Nianna — CHANGES_REQUESTED** [review]
Hi @jespersm
Thanks for finding and fixing the bug. Just one comment for you to fix, otherwise PR is good to go.

File: src/test/java/io/github/nianna/TestUtil.java (hunk 1 above)
Comment (jespersm) [reply src/test/java/io/github/nianna/TestUtil.java:40]: Sure. Pushed in 0979497

**Review by Nianna — APPROVED** [review]
